CREATE SEQUENCE SEQ_SURVEY_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE ORDER;

CREATE TABLE SURVEY(ID NUMBER(38) NOT NULL,
                    NAME VARCHAR2(1000) NOT NULL,
                    DESCRIPTION VARCHAR2(2000),
                    STATUS VARCHAR2(7) DEFAULT 'CREATED' NOT NULL,
                    CONSTRAINT PK_SURVEY PRIMARY KEY (ID),
                    CONSTRAINT CK_SURVEY_STATUS CHECK (STATUS IN ('CREATED', 'OPEN', 'CLOSED'))
                   );

COMMENT ON TABLE SURVEY IS 'Contains the survey basic information.';

COMMENT ON COLUMN SURVEY.ID IS 'Unique table identifier. Incremented using SEQ_SURVEY_ID';
COMMENT ON COLUMN SURVEY.NAME IS 'Survey name';
COMMENT ON COLUMN SURVEY.DESCRIPTION IS 'Survey description';
COMMENT ON COLUMN SURVEY.STATUS IS 'Survey status: CREATED, OPEN, CLOSED';
