CREATE SEQUENCE SEQ_QUESTION_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE ORDER;

CREATE TABLE QUESTION(ID NUMBER(38) NOT NULL,
                    TITLE VARCHAR2(2000) NOT NULL,
                    SURVEY_ID NUMBER(38) NOT NULL,
                    CONSTRAINT PK_QUESTION PRIMARY KEY (ID),
                    CONSTRAINT FK_SURVEY_ID FOREIGN KEY(SURVEY_ID) REFERENCES SURVEY(ID)
                   );

COMMENT ON TABLE QUESTION IS 'Contains the question information.';

COMMENT ON COLUMN QUESTION.ID IS 'Unique table identifier. Incremented using SEQ_QUESTION_ID';
COMMENT ON COLUMN QUESTION.TITLE IS 'Question title';
COMMENT ON COLUMN QUESTION.SURVEY_ID IS 'Foreign key to SURVEY.ID';
